### ISSUE TITLE
Error when using main.exe for Video

### ISSUE THREAD

**Issue by allthetests** [natethegreate/hent-AI#4]
tried testing out the main.exe release, when using the video feature, no frames created

received the attached error message

![error](https://user-images.githubusercontent.com/61926346/76156254-16b2c200-613b-11ea-8eea-631530683946.png)

**Comment by natethegreate** [comment]
What is the video type? It currently only works with .mp4 files. 

But I do want to say that video compatibility will likely be scrapped soon, as we found a much better solution for video mosaics.

**Comment by allthetests** [comment]
.mp4 like was shown in your video, tried it out with a few short .mp4, couldn't get it to work.  If you have a better solution, I'll wait for that.

**Comment by natethegreate** [comment]
Do you think you can send me the clip you used? It looks like an opencv error, so it may have something to do with the file itself.

I should add that only 1 video at a time is required as well

**Comment by allthetests** [comment]
https://filebin.net/1xsh6mnzr23c536j

Was trying to test mosaic and bar style censors in video clips, neither worked for me.  Both videos were originally .webm, converted with VLC using H.265 for test and H.264 for test1.

only tried one video in the folder at a time

**Comment by natethegreate** [comment]
I ran test1.mp4 on my source code, and it worked fine, no opencv errors. There can be errors if the neural network doesnt load properly, like if you have less than 8 gb of ram. As for test.mp4, non standard censors are not supported. Only bars and mosaics.

I will also be releasing an update to the exe very soon.

**Comment by allthetests** [comment]
just to clarify, I am only using the executable file provided.  I didn't download the code.  16 gb of ram.

**Comment by natethegreate** [comment]
Using the v1.4 executable, I have no problem with the video mode. Ensure you have the latest version, if not you can try the code. I have only tried the exe on Windows 10.

**Comment by natethegreate** [comment]
If it is okay with you, I posted the test1 as a gif on the discord on the showcase, if you would like to view the result.

**Comment by allthetests** [comment]
no worries, it was a random mp4 i pulled at random while searching for short clips
