### ISSUE TITLE
Colab version for detecting and masking images only?

### ISSUE THREAD

**Issue by YukiSakuma** [natethegreate/hent-AI#8]
Long story short when I use the main.exe file to detect/mask batch of images my cpu temp goes hot to the 80Cs and I want to avoid this, so is there a guide on how to use the colab version on just detecting and masking the images? And after that download the detected/masked images and use DCP to decensor it.

**Comment by natethegreate** [comment]
Images should now be supported on colab. The last cell has two additional, commented-out commands for bar and mosaic, just make sure to uncomment the one you want and comment out the other two. 

I believe @styler00dollar has a colab with DCP, but cpu should be fine for that.
