### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by esanscoopsers** [natethegreate/hent-AI#9]
First of all, I'm new to github. I'm not much of a programmer myself. So please let me know if I should do anything differently.

Windows 10-64bit
i5-6400
RX570

I followed all the instructions. Got the latest weights.h5, got 4x_FatalPixels_340000_G.pth.
When It runs it seems to work and says I can run deepcreampy but it doesn't make any output with green over the censors. It puts the original into the input_original folder but that's about it. I've attached my test image.

On a side note, does this work with GIFs? Maybe with the video option? I tried testing this one and it didn't work either.

**Comment by natethegreate** [comment]
It does work, but there is some sort of corruption within your image that is preventing the process form starting. I cannot even open it up in Photoshop, but strangley it works in Microsoft Paint. Try finding another source for that image.

GIF is not the same as video. But you can easily convert it to an mp4 or avi and then it will work.

**Comment by natethegreate** [comment]
Also I have removed the images, as GitHub usually does not allow porn.
